'use client'

import { useState, useEffect } from 'react'
import { usePathname } from 'next/navigation'
import { supabase } from '@/lib/supabase'

export type NavBadges = {
  visitas: number
  agenda: number
  panel: number  // urgent alerts generated by the system
}

const SEEN_KEY = 'wm_nav_seen'

type SeenEntry = { date: string; count: number }
type SeenMap = Partial<Record<keyof NavBadges, SeenEntry>>

function readSeen(): SeenMap {
  try { return JSON.parse(localStorage.getItem(SEEN_KEY) ?? '{}') } catch { return {} }
}

function writeSeen(map: SeenMap) {
  try { localStorage.setItem(SEEN_KEY, JSON.stringify(map)) } catch {}
}

/** Sección de la navegación a la que corresponde una ruta. */
function sectionOf(pathname: string): keyof NavBadges | null {
  if (pathname.startsWith('/calendario')) return 'agenda'
  if (pathname.startsWith('/panel')) return 'panel'
  if (pathname.startsWith('/miembros/historico')) return 'visitas'
  return null
}

/**
 * Contadores de la navegación. Lo que se muestra es lo NO revisado: al entrar
 * en una sección se guarda cuántos elementos había y el badge desaparece;
 * vuelve a aparecer solo con lo que llegue después.
 *
 * Lo visto se guarda con la fecha, así que cada día se cuenta de nuevo (los
 * contadores son del día en curso).
 */
export function useNavBadges(): NavBadges {
  const pathname = usePathname()
  const [badges, setBadges] = useState<NavBadges>({ visitas: 0, agenda: 0, panel: 0 })

  useEffect(() => {
    let cancelled = false

    async function load() {
      const now = new Date()
      const todayStr   = now.toISOString().split('T')[0]
      const tomorrowStr = new Date(now.getTime() + 86_400_000).toISOString().split('T')[0]
      const in7days    = new Date(now.getTime() + 7 * 86_400_000)
      const thisMonth  = now.getMonth() + 1
      const thisYear   = now.getFullYear()

      const [
        { count: visitas },
        { count: agenda },
        { count: bono1session },
        { data: expiringBonos },
        { data: membersRaw },
      ] = await Promise.all([
        // People currently inside
        supabase.from('visits').select('id', { count: 'exact', head: true }).is('checked_out_at', null),
        // Today's bookings
        supabase.from('bookings').select('id', { count: 'exact', head: true }).eq('date', todayStr),
        // Bonos with exactly 1 session left
        supabase.from('memberships').select('id', { count: 'exact', head: true }).eq('sessions_remaining', 1),
        // Bonos expiring today or tomorrow
        supabase.from('memberships').select('member_id, expires_at').in('expires_at', [todayStr, tomorrowStr]),
        // Members with children for birthday check
        supabase.from('members').select('id, children').not('children', 'is', null),
      ])

      // Deduplicate expiring bonos by member
      const expiringCount = new Set((expiringBonos ?? []).map((b: any) => b.member_id)).size

      // Birthdays in next 7 days (deduplicated by child name+date)
      const seenBirthdays = new Set<string>()
      let birthdayCount = 0
      for (const member of (membersRaw ?? []) as any[]) {
        for (const child of (member.children ?? []) as any[]) {
          if (!child.birth_date) continue
          const dob = new Date(child.birth_date)
          if (dob.getUTCMonth() + 1 !== thisMonth) continue
          const key = `${child.name}-${child.birth_date}`
          if (seenBirthdays.has(key)) continue
          seenBirthdays.add(key)
          const nextBirthday = new Date(thisYear, now.getMonth(), dob.getUTCDate())
          if (nextBirthday >= now && nextBirthday <= in7days) birthdayCount++
        }
      }

      const raw: NavBadges = {
        visitas: visitas ?? 0,
        agenda:  agenda  ?? 0,
        panel:   (bono1session ?? 0) + expiringCount + birthdayCount,
      }

      // Descontar lo ya revisado; la sección en la que estás se marca vista
      const seen = readSeen()
      const current = sectionOf(pathname)
      const next: NavBadges = { visitas: 0, agenda: 0, panel: 0 }
      let dirty = false

      for (const key of ['visitas', 'agenda', 'panel'] as const) {
        const entry = seen[key]
        const alreadySeen = entry && entry.date === todayStr ? entry.count : 0
        if (key === current) {
          next[key] = 0
          if (!entry || entry.date !== todayStr || entry.count !== raw[key]) {
            seen[key] = { date: todayStr, count: raw[key] }
            dirty = true
          }
        } else {
          next[key] = Math.max(0, raw[key] - alreadySeen)
        }
      }
      if (dirty) writeSeen(seen)
      if (!cancelled) setBadges(next)
    }

    load()
    const t = setInterval(load, 60_000)
    return () => { cancelled = true; clearInterval(t) }
  }, [pathname])

  return badges
}
