'use client'

import { useState, useEffect } from 'react'
import { supabase } from '@/lib/supabase'

export type NavBadges = {
  visitas: number
  agenda: number
  panel: number  // urgent alerts generated by the system
}

export function useNavBadges(): NavBadges {
  const [badges, setBadges] = useState<NavBadges>({ visitas: 0, agenda: 0, panel: 0 })

  useEffect(() => {
    async function load() {
      const now = new Date()
      const todayStr   = now.toISOString().split('T')[0]
      const tomorrowStr = new Date(now.getTime() + 86_400_000).toISOString().split('T')[0]
      const in7days    = new Date(now.getTime() + 7 * 86_400_000)
      const thisMonth  = now.getMonth() + 1
      const thisYear   = now.getFullYear()

      const [
        { count: visitas },
        { count: agenda },
        { count: bono1session },
        { data: expiringBonos },
        { data: membersRaw },
      ] = await Promise.all([
        // People currently inside
        supabase.from('visits').select('id', { count: 'exact', head: true }).is('checked_out_at', null),
        // Today's bookings
        supabase.from('bookings').select('id', { count: 'exact', head: true }).eq('date', todayStr),
        // Bonos with exactly 1 session left
        supabase.from('memberships').select('id', { count: 'exact', head: true }).eq('sessions_remaining', 1),
        // Bonos expiring today or tomorrow
        supabase.from('memberships').select('member_id, expires_at').in('expires_at', [todayStr, tomorrowStr]),
        // Members with children for birthday check
        supabase.from('members').select('id, children').not('children', 'is', null),
      ])

      // Deduplicate expiring bonos by member
      const expiringCount = new Set((expiringBonos ?? []).map((b: any) => b.member_id)).size

      // Birthdays in next 7 days (deduplicated by child name+date)
      const seen = new Set<string>()
      let birthdayCount = 0
      for (const member of (membersRaw ?? []) as any[]) {
        for (const child of (member.children ?? []) as any[]) {
          if (!child.birth_date) continue
          const dob = new Date(child.birth_date)
          if (dob.getUTCMonth() + 1 !== thisMonth) continue
          const key = `${child.name}-${child.birth_date}`
          if (seen.has(key)) continue
          seen.add(key)
          const nextBirthday = new Date(thisYear, now.getMonth(), dob.getUTCDate())
          if (nextBirthday >= now && nextBirthday <= in7days) birthdayCount++
        }
      }

      setBadges({
        visitas: visitas ?? 0,
        agenda:  agenda  ?? 0,
        panel:   (bono1session ?? 0) + expiringCount + birthdayCount,
      })
    }

    load()
    const t = setInterval(load, 60_000)
    return () => clearInterval(t)
  }, [])

  return badges
}
